### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by SurajBhari** [splewis/csgo-executes#12]
so after the today's update with BR mode being launched 
The plugin just F up , it just crashes whenever someone try to choose a team , i know You have already fixed retakes , Please fix this as fast as possible

ALSO

you can see enemy on radar through smokes 
I think it is csutils issue 

TY in advance <3 ;) . appreciate your hard work

**Comment by splewis** [comment]
Update to a newer sourcemod snapshot. This isn't a issue with the plugin, there's nothing for me to fix.

And: https://github.com/splewis/csgo-practice-mode/issues/71
