### ISSUE TITLE
UPD

### ISSUE THREAD

**Issue by d0kt0r** [splewis/csgo-executes#13]
Hello! Can you update this plugin, add something new?

**Comment by MoritzLoewenstein** [comment]
Why dont you tell what your Problem with this Plugin is?

**Comment by splewis** [comment]
When making a request, usually you should describe what it is.

**Comment by d0kt0r** [comment]
I have no problems, just the mode itself is boring. So I asked, could you update it?

**Comment by SurajBhari** [comment]
maybe add a system by which the more the kills you get the better your weapons will be 
and add a option by which you can also choose your pistol which will be given if u had good kills ;-;
RIP ENGLISH ;-;

**Comment by splewis** [comment]
[Pull requests](https://github.com/splewis/csgo-executes/pulls) welcome.
