### ISSUE TITLE
Language phrase "JoinedQueueMessage" not found

### ISSUE THREAD

**Issue by SurajBhari** [splewis/csgo-executes#14]
L 12/25/2018 - 03:50:30: [SM] Exception reported: Language phrase "JoinedQueueMessage" not found 
                                        (arg 4)
L 12/25/2018 - 03:50:30: [SM] Blaming: executes.smx
L 12/25/2018 - 03:50:30: [SM] Call stack trace:
L 12/25/2018 - 03:50:30: [SM]   [0] FormatNativeString
L 12/25/2018 - 03:50:30: [SM]   [1] Line 50, ./scripting/executes/natives.sp::Native_PluginMessage
L 12/25/2018 - 03:50:30: [SM]   [3] Executes_Message
L 12/25/2018 - 03:50:30: [SM]   [4] Line 620, ./scripting/executes.sp::PlacePlayer
L 12/25/2018 - 03:50:30: [SM]   [5] Line 594, ./scripting/executes.sp::Command_JoinTeam

ANYONE KNOW HOW TO FIX IT ^

**Comment by B3none** [comment]
You need to upload the translation file if you haven't already. 

Also please make sure that the phrase "JoinedQueueMessage" exists.

**Comment by AG4lyf** [comment]
https://drive.google.com/file/d/1SpH2gQ4LYcjUDRHJbxhctibatNFslPO-/view?usp=drivesdk


Here u go 
Was a bit busy so a little late reply

**Comment by AG4lyf** [comment]
Any update on this ?

Cuz this is the only error in the whole server

and that feels odd to me

**Comment by shaikhnedab** [comment]
manually copy paste the text from translation file from github to your server.(don't upload .txt file. open .txt file on github copy whole file paste in your server .txt file)
