### ISSUE TITLE
didn't understand how to edit the mod

### ISSUE THREAD

**Issue by BarVazz** [splewis/csgo-executes#16]
Hi,
I'm trying to edit the MOD as you wrote at: https://github.com/splewis/csgo-executes
Do you have perhaps a more detailed guide on how to work with the MOD?

**Comment by splewis** [comment]
I don't understand what you are asking.

There's installation instructions here: https://github.com/splewis/csgo-executes#installation

It's the same as pretty much every other sourcemod plugin.

**Comment by BarVazz** [comment]
I didn't understand what Is A friendliness and B friendliness in CT side, how do I know how much do I need to put each side,I tried to read your example to the map de_cache but I didn't understand why there are 5 spawns in B, 3 in mid and 1 in a, if I want to put only 2 spawns in B and 1 mid, and 2 a? 
And what is the meaning of likehood?
And last question, where can I get a plugin of a text-hud
That writing to the T side where they need to go, and what they need to do?

**Comment by splewis** [comment]
> what Is A friendliness and B friendliness in CT side, 

Read https://github.com/splewis/csgo-executes#creating-executes-and-spawns.

> I tried to read your example to the map de_cache but I didn't understand why there are 5 spawns in B, 3 in mid and 1 in a, if I want to put only 2 spawns in B and 1 mid, and 2 a?


I don't know what example you're talking about. There can be 5 spawns without them all being selected. It's randomized. You can usually picture a spawn from each friendliness is chosen each round, but it's difficult to explain without just explaining the algorithm: https://github.com/splewis/csgo-executes/blob/master/scripting/executes/execute_setup.sp#L260. Note all the per-map constants underneath that.

> And last question, where can I get a plugin of a text-hud
That writing to the T side where they need to go, and what they need to do?

Not in this plugin.

**Comment by SurajBhari** [comment]
> And last question, where can I get a plugin of a text-hud
That writing to the T side where they need to go, and what they need to do?


https://www.dropbox.com/s/txssrtvl78bkpxu/executeshud.smx?dl=0

u can use this 
i made it a long ago 
also it only print for T side
