### ISSUE TITLE
Question about spawns with the nades

### ISSUE THREAD

**Issue by Tene96** [splewis/csgo-executes#18]
Hi, so I tried to put spawns for smokes and molotovs as you said in the installation guide, but i do some thing wrong, somehow Players spawns where the smoke/molotov are throwing away. 

After I did a nade spawn, i change the nades spawns to required and the T side players spawns to optional is it right?

**Comment by SurajBhari** [comment]
dont set anything to required 
set everything to optional 
as plugin choose execute on the basis of the no. of players online
if u still cant do it 
i have configs and i can sell those ;-; 
sorry for my grammar

**Comment by splewis** [comment]
>  Players spawns where the smoke/molotov are throwing away.

I don't know what you mean.

>  i change the nades spawns to required and the T side players spawns to optional is it right?

You can do whatever you want. I typically say spawns that throw smokes required and most the others as optional.

**Comment by Tene96** [comment]
Thank you for your answer, it took me a few min, but I understood how it works.

Is there any way to disable when the round starts that freezing for 2 sec of the terror?

When I start the game, terrorist needs to  wait 2 sec before the can start eventhough freezetime ends,it happens i think because of the grenades

**Comment by SurajBhari** [comment]
its a cvar 
you can disable it in csgo/cfg/sourcemod/exeuctes/exeucutes.cfg
line 19 
sm_executes_default_extra_freeze_time

i keep it as
sm_executes_default_extra_freeze_time "1"

**Comment by Tene96** [comment]
Thank you very much :D 
Last thing you dont have to do it , but do you know where i can find a plugin that when a player writes !vp 
he vote for only pistols round , and when he writes !vd he votes for only deagle rounds ? 
i want to add it to my execute server and i cant find it :(

**Comment by splewis** [comment]
> do you know where i can find a plugin

No.
