### ISSUE TITLE
Smokes don't launched at the end of freeze time

### ISSUE THREAD

**Issue by beldah** [splewis/csgo-executes#2]
Hello,

For an unknow reason on Mirage, the stuff is correctly launch after the freeze time,
but on cache map, the stuff don't want launch.

Do you have an idea about my problem ?
ps : I checked and the line "grenade type" contain "smoke"

Best Regards,
Beldah

**Comment by timche** [comment]
Can you show your `de_cache.cfg` in `addons/sourcemod/configs/executes` please?

**Comment by beldah** [comment]
Fixed, I need just after configurate the stuffs to reload the map.

Great Thanks.
