### ISSUE TITLE
do tick rate matters ?

### ISSUE THREAD

**Issue by SurajBhari** [splewis/csgo-executes#20]
well , i was half through making executes making new map de_ruby config , and there are no smokes i can find , so i was making my own 
half through i realized that my tickrate was set to 64 . but my server is on 128 , 
i don't think tickrate matters as they are not real smokes ?
can you confirm it ?

**Comment by splewis** [comment]
> i don't think tickrate matters as they are not real smokes ?
can you confirm it ?

I honestly don't know the answer, and the answer is subject to change in the future anyway. Using 64-tick anything is probably a bad idea.
