### ISSUE TITLE
Configs 

### ISSUE THREAD

**Issue by SurajBhari** [splewis/csgo-executes#21]

**Comment by AG4lyf** [comment]
As an unnamed corporation forcefully took my configs , so i decide to make it public :)
Vertigo is untested * and surely contains bugs after last map change
[config.zip](https://github.com/splewis/csgo-executes/files/3284497/config.zip)

**Comment by AG4lyf** [comment]
Also these configs are 100 % tested , with maxplayers set to 10 , 
they are made and improved to make it balanced and fair 
and yeah 
they contain smokes
