### ISSUE TITLE
TAKE MY CONFIGS 

### ISSUE THREAD

**Issue by SurajBhari** [splewis/csgo-executes#22]
[executes.zip](https://github.com/splewis/csgo-executes/files/3346257/executes.zip)
just take it , merge it , 
an company forcefully took them from me  , so i am making it public :) 
these are 100 % balanced and tested . with maxplayers 10 . , v̶e̶r̶t̶i̶g̶o̶ ̶m̶a̶y̶ ̶c̶o̶n̶t̶a̶i̶n̶ ̶b̶u̶g̶s̶ ( UPDATED )
PEACE

**Comment by JensPanis** [comment]
@AG4lyf I love you!

**Comment by rpkaul** [comment]
Thank you for share...best of luck for your future ... 
Launch 100 servers against that company

**Comment by splewis** [comment]
You can make another repo for whatever things you want. I'm not planning to maintain any configs going forward, they are too opinionated and require changes too often.

**Comment by SurajBhari** [comment]
I would appreciate If you mention it in the post :) 
https://github.com/AG4lyf/configs
