### ISSUE TITLE
After the update on 2.28.18 - Smokes no longer are thrown

### ISSUE THREAD

**Issue by GabeHirakawa** [splewis/csgo-executes#3]
As the title states, smokes are no longer thrown as of this update. I'm unsure of where the break down is happening. Just thought I would make an issue to get more eyes on it.

I've tried Unstable 1.10, 1.9 and stable 1.8 and all have the same effect. Playing on the official servers also shows that this is more widespread.

**Comment by splewis** [comment]
> Playing on the official servers also shows that this is more widespread.

... what servers does that mean? matchmaking?

**Comment by GabeHirakawa** [comment]
Sorry, I should've been more specific. Your whiffcity servers is what I meant by "official"

**Comment by ghost** [comment]
Also to add on to this, When everyone dies the round no longer ends, Smokes arent thrown and it seems that when you die, you are spectating the bot, when you hit the number keys it changes to a normal players view.

**Comment by splewis** [comment]
Yeah, the bot the csutils plugin spawns seems to be in a messed up state (he's probably not being killed because the smokes never get thrown, so he doesn't die since there are still nades in the active grenade queue, thus the round is continuing because there is another T alive).

To anyone that wants to help fix this: the issue is in the [csutils](https://github.com/splewis/csgo-practice-mode/blob/master/scripting/csutils.sp) plugin, so that's where the fix is needed. I probably won't even begin looking at the problem until Friday (or later).

**Comment by GabeHirakawa** [comment]
I'll see if I can't figure it out. If I can figure it out I'll make a pull request.

Thanks splewis.

**Comment by splewis** [comment]
Going to update in https://github.com/splewis/csgo-practice-mode/issues/64 from now on.

**Comment by splewis** [comment]
I just pushed a practicemode update which "should" fix this.

To test this update, download from https://ci.splewis.net/job/csgo-executes/lastSuccessfulBuild/ and update BOTH csutils.smx and executes.smx.

Edit: I've seen some crashing in my own servers with this update. Use at your own risk. If you can provide crash dumps via accelerator, that will be useful.

**Comment by GabeHirakawa** [comment]
So, as you said would happen my servers have been crashing. I actually witnessed it myself and I believe that the crash is due to when the smokes thrown hit a player before popping or if it sticks that player.

Example: I was sitting in Connector on Train, the Connector smoke flew and hit my feet in the way that would cause me to be stuck on the smoke, at that exact moment it crashed.

edit here are my crash ids: `NRUJ-NR5X-F6XR 6WWY-4HJM-YL6T P4W5-SWUW-AULY
`

**Comment by splewis** [comment]
Yes: https://github.com/splewis/csgo-practice-mode/issues/68

**Comment by splewis** [comment]
Fixed. 

Yes, the nades behave a little differently, see https://github.com/splewis/csgo-practice-mode/issues/71
