### ISSUE TITLE
Gun menu

### ISSUE THREAD

**Issue by ghost** [splewis/csgo-executes#30]
Would you add a weapon menu similar to the retake plugin? I want to cancel the force round and choose to change pistols. Can you get us to arrange this?

**Comment by ghost** [comment]
**codes:**

- https://github.com/northeaster/csgo-executes/commit/d5fd830abb131902c5a52e8a8fe8f1dd72ff67e4

- https://github.com/northeaster/csgo-executes/commit/eb1a3e46cd6e94f9ea50ff102080ebe5e031a343

**picture:**

- https://steamuserimages-a.akamaihd.net/ugc/787498487317288409/78B79868A428F3EEDC03C5CE68C5F0EEA289025A/

**I set the pistol preference myself. When I click 2 and 4, the pistol do not change. This is the problem. Warning compiles. it may not work because of this warning?**

```
//// executes.sp
//
// C:\Users\User\Desktop\sourcemod\addons\sourcemod\scripting\executes.sp(355) : warning 213: tag mismatch
// C:\Users\User\Desktop\sourcemod\addons\sourcemod\scripting\executes.sp(356) : warning 213: tag mismatch
// C:\Users\User\Desktop\sourcemod\addons\sourcemod\scripting\executes.sp(460) : warning 213: tag mismatch
// Code size:           141832 bytes
// Data size:           144560 bytes
// Stack/heap size:      16384 bytes
// Total requirements:  302776 bytes
//
// 3 Warnings.
//
// Compilation Time: 3,34 sec
// ----------------------------------------
```

**Comment by m0rbit1989** [comment]
I would also like a weapon menu as in retake
