### ISSUE TITLE
Falling back to a random T to be bomb carrier: map

### ISSUE THREAD

**Issue by SurajBhari** [splewis/csgo-executes#33]
I made the configs and everything worked without any error for a while then 
everyone started to get an error as follows:
```L 05/23/2020 - 16:22:30: [executes.smx] Falling back to a random T to be bomb carrier: map=de_dust2, execute id=4, tCount=3```
I have seen my configs and everything seems to be fine . can you explain what this is for? 
I don't see an option that can fix it tho.
Wonder you can tell me what is wrong.

**Comment by splewis** [comment]
The logic [here](https://github.com/splewis/csgo-executes/blob/1ced43d1395c64d3eb7eea0588d8b53f55609920/scripting/executes/execute_setup.sp#L151-L190) will explain how the bomb carrier is chosen.

I would guess the 'bomb friendliness scores' are too low, or all spawns were marked as lurker spawns. I can't say without the actual config though.

**Comment by SurajBhari** [comment]
This was infact a config issue.
