### ISSUE TITLE
Smokes config

### ISSUE THREAD

**Issue by Tarek8220** [splewis/csgo-executes#40]
Since i already have an retake server i decided to get and execute and i tried and tried so hard to put the smokes and make everything works perfectly BUT I CANT :( So i hope there is any kind persons out there who may have some saved files for smokes spawns and everything rdy they can share with me :)

**Comment by rpkaul** [comment]
@Tarek8220 https://github.com/AG4lyf/configs/tree/master/addons/sourcemod/configs/executes
