### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by kmsraidboss** [splewis/csgo-executes#6]
I seem to be having the following issue when attempting to compile this plugin

`
// G:\CSGO\a_Plugins\Compile\executes.sp(353) : error 017: undefined symbol "PQ_Clear" 
// G:\CSGO\a_Plugins\Compile\executes.sp(354) : error 017: undefined symbol "PQ_Clear" 
// G:\CSGO\a_Plugins\Compile\executes.sp(879) : warning 217: loose indentation 
// G:\CSGO\a_Plugins\Compile\executes.sp(977) : error 017: undefined symbol "PQ_Clear"
 // G:\CSGO\a_Plugins\Compile\executes.sp(986) : warning 213: tag mismatch 
// G:\CSGO\a_Plugins\Compile\executes.sp(995) : warning 213: tag mismatch
`

This is happening when compiling on both the current stable SM release and the dev release. I've attempted to troubleshoot and have ensured all dependencies are in place in their correct paths. Any help on this would be appreciated.

**Comment by splewis** [comment]
Did you actually look at include/priorityqueue.inc? The errors make it seems like you didn't copy that file correctly.

**Comment by kmsraidboss** [comment]
The file exists in the includes folder and is unedited. Before initially creating this issue, I went through pretty thoroughly to ensure everything was included and all paths were correct. I'm not a pro by any means and could have overlooked something, so that's why I brought this issue here since there is no active AM thread on this plugin. I'm not sure what could have gone wrong during the copy process.

**Comment by splewis** [comment]
Well, I can't reproduce any issues - my build is fine, and so is the [travis build](https://travis-ci.org/splewis/csgo-executes/jobs/366679319), which is compiled from [these instructions](https://github.com/splewis/csgo-executes/blob/master/.travis.yml#L12).

I don't know how to help here.

**Comment by SurajBhari** [comment]
Had same issue 
was missing "PQ_Clear" function in priorityqueue.inc file. for some reason, it got overwritten somewhere in the process.

edit - https://github.com/splewis/csgo-executes/blob/f9ce631206136c9fad00fdcd5b23a73449cd92b1/scripting/include/priorityqueue.inc#L94 i got it from here.
